/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package GUI;

import CustomComponents.CollaborationItem;
import CustomComponents.WrapLayout;
import Pojo.Invite;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.util.ArrayList;
import javax.swing.JPanel;

/**
 *
 * @author UyNguyen.ITUS
 */
public class MyListCollaboration extends javax.swing.JPanel {
    JPanel panel_MyDocs;

    /**
     * Creates new form MyListCollaboration
     */
    public MyListCollaboration(ArrayList<Invite> lst_Invite, JPanel panel_MyDocs) {
        initComponents();
        
        this.panel_MyDocs = panel_MyDocs;
        Dimension dim = Toolkit.getDefaultToolkit().getScreenSize();

        this.setLocation(dim.width - this.getSize().width / 2, dim.height - this.getSize().height / 2);
        panel.setLayout(new WrapLayout(java.awt.FlowLayout.LEFT, 5, 5));
        int size = lst_Invite.size();
        for (int i = 0; i < size; i++) {

            Invite temp = lst_Invite.get(i);
            panel.add(new CollaborationItem(temp.getId(), temp.getDoc_Code(), temp.getId_sender(), temp.getUsername_Sender(), temp.getDate_Invite(), temp.getDoc_title()));
        }
    }

    public JPanel getPanel_MyDocs() {
        return panel_MyDocs;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        panel = new javax.swing.JPanel();

        panel.setBackground(new java.awt.Color(102, 204, 255));

        javax.swing.GroupLayout panelLayout = new javax.swing.GroupLayout(panel);
        panel.setLayout(panelLayout);
        panelLayout.setHorizontalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 868, Short.MAX_VALUE)
        );
        panelLayout.setVerticalGroup(
            panelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 406, Short.MAX_VALUE)
        );

        jScrollPane1.setViewportView(panel);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1)
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel panel;
    // End of variables declaration//GEN-END:variables
}
